### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by jrschumacher** [Fesaa/iCalMerger#3]
Hi @Fesaa 👋

I wanted to see how you'd handle the first PR before reaching out and sending a few more. This is a great idea and something I'd been considering doing. Some of my PRs will be a bit heavier, but with the goal of making testing easier which I'll also add. 

I'll also add some features too 😄 feel free to ask any questions or for changes.

**Comment by Fesaa** [comment]
Heya!

I've made this project for a very specific issue I've had, which it has solved for me. I personally don't really have a direction I want to go with this project, at the moment.

So feel free to implement whatever you need from this project, and I'll be happy to see it fit in

That being said, my apologies for the sloppy code here and there, haha.
